name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Enable pnpm
        run: corepack enable && corepack prepare pnpm@9.0.0 --activate

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Dedupe check
        run: pnpm dedupe --check

      - name: OSV dependency scan
        uses: google/osv-scanner-action@v2.2.2
        with:
          # Include HEAD if you have no lockfiles; see action release notes
          scan-args: |
            --recursive
            ./
            --include-git-root
