# .github/workflows/ci.yml
name: CI

on:
  push:
  pull_request:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node (LTS) + pnpm cache
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      # 🔑 Install pnpm on PATH for all later steps
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Verify tools
        run: |
          node -v
          pnpm -v

      - name: Install deps (frozen)
        env: { CI: 'true' }
        run: pnpm install --frozen-lockfile

      - name: Dedupe check
        run: pnpm dedupe --check

      - name: Lint
        run: pnpm -w lint

      - name: Typecheck
        run: pnpm -w typecheck

      - name: Tests
        run: pnpm -w test

      - name: Security audit (OSV)
        run: pnpm -w audit
