name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Install pnpm globally FIRST so it's on PATH
      - name: Install pnpm
        run: npm i -g pnpm@9

      # Prove pnpm is available
      - name: Verify tools
        run: |
          echo "PATH=$PATH"
          which node
          node -v
          which pnpm
          pnpm -v

      # If your project lives in apps/web, uncomment the working-directory:
      - name: Install deps
        # working-directory: apps/web
        run: pnpm install --no-frozen-lockfile
